version: '2'

services:
  ui:
    image: hypriot/rpi-dockerui
    container_name: docker-ui
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    expose:
      - 9000
    ports:
      - 80:9000

  web:
    image: scornflake/ark-evolved

    container_name: ark4

    environment:
      - SESSIONNAME=TheOthers2
      - SERVERMAP=Ragnarok
      - SERVERPASSWORD=othersagain5
      - ADMINPASSWORD=muppet
    ports:
      - 7777:7777/udp
      - 7778:7778/udp
      - 27015:27015/udp
      - 27015:27015
      - 32330:32330
      - 7778:7778

    restart: always

    depends_on:
      - worker

  worker:
    image: johncclayton/electric-pi-worker

    container_name: electric-worker
    command: sh -x /www/run_zmq_worker.sh
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb

    restart: always
